spring:
  data:
    mongodb:
      uri: mongodb+srv://tttuser:tttpassword@cluster0.mbof3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: ttt

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.email}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4000